import pandas as pd
import numpy as np


INPUT = "data/processed/pilot_monthly_development_panel.parquet"


def main():
    print("=" * 80)
    print("EXTREME DIFFICULTY-GAP ANALYSIS")
    print("=" * 80)

    df = pd.read_parquet(INPUT)

    # Primary sample.
    df = df[
        df["rating_at_month_end"].notna()
        & (df["accepted_rated_count"] > 0)
        & df["rating_gain_3m"].notna()
        & df["difficulty_gap_p75"].notna()
    ].copy()

    print()
    print(f"Observations : {len(df)}")
    print(f"Users        : {df['handle'].nunique()}")

    # ------------------------------------------------------------------
    # Extreme observations
    # ------------------------------------------------------------------

    for threshold in [500, 750, 1000, 1500]:
        high = df[
            df["difficulty_gap_p75"] >= threshold
        ].copy()

        low = df[
            df["difficulty_gap_p75"] <= -threshold
        ].copy()

        print()
        print("=" * 80)
        print(f"THRESHOLD: |gap| >= {threshold}")
        print("=" * 80)

        print()
        print("HIGH GAP")
        print("-" * 80)

        print(f"Observations : {len(high)}")
        print(f"Users        : {high['handle'].nunique()}")

        if len(high) > 0:
            print(
                f"Median gap  : {high['difficulty_gap_p75'].median():.2f}"
            )
            print(
                f"Median count: {high['accepted_rated_count'].median():.1f}"
            )

        print()
        print("LOW GAP")
        print("-" * 80)

        print(f"Observations : {len(low)}")
        print(f"Users        : {low['handle'].nunique()}")

        if len(low) > 0:
            print(
                f"Median gap  : {low['difficulty_gap_p75'].median():.2f}"
            )
            print(
                f"Median count: {low['accepted_rated_count'].median():.1f}"
            )

    # ------------------------------------------------------------------
    # Concentration of high-gap observations
    # ------------------------------------------------------------------

    print()
    print("=" * 80)
    print("HIGH-GAP CONCENTRATION")
    print("=" * 80)

    high = df[
        df["difficulty_gap_p75"] >= 750
    ].copy()

    if len(high) == 0:
        print("No observations with gap >= 750.")
        return

    counts = (
        high.groupby("handle")
        .size()
        .sort_values(ascending=False)
    )

    print(f"Total high-gap observations : {len(high)}")
    print(f"Users with high-gap months  : {len(counts)}")

    print()
    print("OBSERVATIONS PER USER")
    print("-" * 80)
    print(counts.describe())

    print()
    print("Top users:")
    print(counts.head(20).to_string())

    # ------------------------------------------------------------------
    # Share of extreme observations generated by top users
    # ------------------------------------------------------------------

    print()
    print("=" * 80)
    print("CONCENTRATION SHARE")
    print("=" * 80)

    total = len(high)

    for n in [1, 3, 5, 10]:
        share = counts.head(n).sum() / total

        print(
            f"Top {n:2d} users account for "
            f"{share:.2%} of gap >= 750 observations"
        )

    # ------------------------------------------------------------------
    # Inspect the actual extreme observations
    # ------------------------------------------------------------------

    print()
    print("=" * 80)
    print("TOP 30 EXTREME OBSERVATIONS")
    print("=" * 80)

    columns = [
        "handle",
        "month",
        "accepted_rated_count",
        "rating_at_month_end",
        "practice_p75",
        "difficulty_gap_p75",
        "rating_gain_3m",
    ]

    print(
        df[
            columns
        ]
        .sort_values(
            "difficulty_gap_p75",
            ascending=False,
        )
        .head(30)
        .to_string(index=False)
    )


if __name__ == "__main__":
    main()
